# Generated by Django 5.0.1 on 2024-01-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('On shelf', 'on shelf')], default='On shelf', max_length=15),
        ),
    ]
