# Generated by Django 5.0.1 on 2024-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_member_name_member_address_member_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_no',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
