# Generated by Django 5.0.1 on 2024-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_member_id_no_alter_member_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.CharField(default='12345678', max_length=8),
            preserve_default=False,
        ),
    ]
