# Generated by Django 5.0.1 on 2024-01-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_member_id_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='id_no',
            new_name='national_id',
        ),
    ]
