# Generated by Django 5.0.1 on 2024-01-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_id_no_member_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='national_id',
        ),
    ]
