# Generated by Django 5.0.1 on 2024-01-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_book_category_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
