# Generated by Django 5.0.1 on 2024-01-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_transaction_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='member_id',
            new_name='member',
        ),
    ]
