# Generated by Django 5.0.1 on 2024-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_debt_transaction_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('returned', 'returned'), ('pending', 'pending'), ('extended', 'extended')], default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
