# Generated by Django 5.0.1 on 2024-01-26 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(default='/home/fhadhul/Desktop/fhadhul/library/static/images/dummy.jpg', null=True, upload_to='image/profile_imgs'),
        ),
    ]
