# Generated by Django 5.0.1 on 2024-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_member_member_since_alter_member_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copy_ids',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
