# Generated by Django 5.0.1 on 2024-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_book_copy_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copy_ids',
            field=models.TextField(blank=True),
        ),
    ]
