# Generated by Django 5.0.1 on 2024-01-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_book_copy_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(default='/home/fhadhul/Desktop/fhadhul/library/static/images/dummy1.png', null=True, upload_to='image/profile_imgs'),
        ),
    ]
