# Generated by Django 5.0.1 on 2024-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_book_description_alter_member_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(default='/home/fhadhul/Desktop/fhadhul/library/static/image/dummy1.png', null=True, upload_to='image/profile_imgs'),
        ),
    ]
