# Generated by Django 5.0.1 on 2024-01-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_member_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(default='static/image/dummy1.png', null=True, upload_to='image/profile_imgs'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(default='2024-02-02'),
            preserve_default=False,
        ),
    ]
