# Generated by Django 5.0.1 on 2024-02-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_librarian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
