# Generated by Django 5.0.1 on 2024-02-06 00:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_transaction_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
